<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="BOBServiciosUtilService"
     targetNamespace="http://action.cu.ws.soa.lucasian.com/"
     xmlns:ns2="http://action.cu.ws.soa.lucasian.com/"
     xmlns:ns1="http://ifaces.cu.ws.soa.lucasian.com/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="IBOBServiciosUtil_PL">
        <plnk:role name="IBOBServiciosUtil_Role">
            <plnk:portType name="ns1:IBOBServiciosUtil"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://action.cu.ws.soa.lucasian.com/" location="http://labs.lucasian.com/bob.soa.ws/BOBServiciosUtilService?wsdl"/>
</wsdl:definitions>
